### ISSUE TITLE
Use insert-directory-program instead of ls

### ISSUE THREAD

**Issue by rgrinberg** [yqrashawn/fd-dired#10]
On macos, dired works by customizing `insert-directory-program` to use the gnu ls binary (`gls`). It would be nice if fd-dired would respect this configuration.

**Comment by mkleehammer** [comment]
Seeing the same thing here.  Does not work on macOS out-of-the-box.

**Comment by kaiwk** [comment]
Yes, It's not a good idea to hardcoded `ls`. BSD `ls` doesn't have flag `--quoting-style`. Or one can [override all commands with GNU utils on Mac with `coreutils`](https://stackoverflow.com/a/57973942/9212213).
