### ISSUE TITLE
Transient interface

### ISSUE THREAD

**Issue by xFA25E** [yqrashawn/fd-dired#23]
Hey! I've maid a [transient interface for fd-dired](https://gist.github.com/xFA25E/a13e5513b0457bb1848ae0f68b0a72f5).

Do you want me to make it a PR? Or should I keep it as a separate package?

Maybe you want to keep `fd-dired` minimal like `dired-rsync` does, which has a separate `dired-rsync-transient` package. Because this contribution would add a dependency on `transient` (and more code to maintain), of course.

It looks like this:
![](https://github.com/xFA25E/images/raw/main/fd-dired.png)

**Comment by yqrashawn** [comment]
Please keep it as a separate package if still interested. Thanks
