### ISSUE TITLE
Files with spaces in names don't open 

### ISSUE THREAD

**Issue by GrinDeg** [yqrashawn/fd-dired#4]
Looks like when there is a whitespace in one of the filenames it get's surrounded by single quotes 
`'folder/file name.txt' `
instead of 
`folder/file name.txt`
and dired can't open it(says, that file doesn't exists)

**Comment by stardiviner** [comment]
Any updates on this issue?

**Comment by stardiviner** [comment]
This issue should be fixed too. Can be closed.

**Comment by grolongo** [comment]
@GrinDeg hello, can you provide the command you used that didn't work with BSD ls?

I've been using fd-dired on macOS without `--quoting-style=literal` option and I don't have any problem with spaces in filenames.
