### ISSUE TITLE
Add an option for which `ls' is used

### ISSUE THREAD

**Issue by ylluminarious** [yqrashawn/fd-dired#7]
`fd-dired-ls-option` is defined as:

```
(defvar fd-dired-ls-option '("| xargs -0 ls -ld --quoting-style=literal" . "-ld"))
```

Unfortunately, `--quoting-style` is a flag only available on GNU `ls`, which is not the `ls` used by default on macOS. I have GNU `ls` installed as `gls` in my PATH. It would be nice to specify that `gls` be used here instead of just whatever `ls` happens to be in the PATH.

Could you make a variable called `fd-dired-ls-command` which allows a user to specify the name of the `ls` command which is used?

**Comment by yqrashawn** [comment]
Please use the `insert-directory-program` variable.

eg. `(setq insert-directory-program "/usr/local/bin/gls")

**Comment by ylluminarious** [comment]
@yqrashawn Thanks, although mine is already set to `gls`, so that apparently didn't solve the issue. I decided to put the following in my init file, which did fix the issue:

```lisp
(with-eval-after-load 'fd-dired
  (setq fd-dired-ls-option '("| xargs -0 gls -ld --quoting-style=literal" . "-ld")))
```
